### ISSUE TITLE
Python bindings?

### ISSUE THREAD

**Issue by probonopd** [thesquash/stlwrt#10]
Are there Python bindings available or planned?

https://twitter.com/Ericbsd/status/1497560282947858434

**Comment by thesquash** [comment]
Python bindings should be inherited from GTK+ 2, and GTK+ 3-compatible ones shouldn't be too hard to add.  These days, Python bindings (and bindings for other languages too) are provided from the generic `gobject-introspection` project, which programmatically analyzes the source and header files of the library in question.  As such it won't be a terribly difficult venture (I think) to create Python bindings for STLWRT.

Plus, the legacy Python bindings like PyGTK should (the operative word being ***should***) still work with STLWRT anyway, just by extension of STLWRT aiming to remain compatible with GTK+ 2 applications -- all but the oldest of them.

**Comment by probonopd** [comment]
Thanks for the clarification, that's great to hear.

Thanks for this project. It is very much needed.
