### ISSUE TITLE
How to build STLWRT

### ISSUE THREAD

**Issue by Melchizedek6809** [thesquash/stlwrt#8]
I have been looking through the repo a bit but have found no Makefile or something similar, how does one build STLWRT (even if it's still buggy)?
And how do you go about running/testing your code, LD_PRELOAD?

Have a nice day,
Ben

**Comment by thesquash** [comment]
Sorry to leave such a terse response, but I've been very tied up lately.

However, I've resumed writing STLWRT code after a long hiatus, and the README should tell you all that you need to know about "building" STLWRT right now.  These instructions will eventually change, though!

**Comment by Melchizedek6809** [comment]
No problem, thank you for the Reply.
